# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorldCli < Formula
  desc "testing homebrew tap"
  homepage "https://github.com/j--wong/hello-world-cli"
  version "0.0.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/j--wong/hello-world-cli/releases/download/v0.0.4/hello-world-cli_0.0.4_macOS_amd64.tar.gz"
      sha256 "bd1251b6f68dbbfdb2c8eccc59a70c2e4533460665be1a579f3c42fd1ed2b2a1"
    end
    if Hardware::CPU.arm?
      url "https://github.com/j--wong/hello-world-cli/releases/download/v0.0.4/hello-world-cli_0.0.4_macOS_arm64.tar.gz"
      sha256 "a82fae03fedde5ab0f7fccf16476ec057e0d33db17e7568e58aa4a8d75fb7b6f"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/j--wong/hello-world-cli/releases/download/v0.0.4/hello-world-cli_0.0.4_linux_arm64.tar.gz"
      sha256 "bb6b65a2129af6d72cf67dbff0d8d2e4a3c9919316a7680a72cc462065770fcd"
    end
    if Hardware::CPU.intel?
      url "https://github.com/j--wong/hello-world-cli/releases/download/v0.0.4/hello-world-cli_0.0.4_linux_amd64.tar.gz"
      sha256 "cfc5fa406c709caf8794c0c2219f8cfb082e44eb567d81befc4a0093c8a72126"
    end
  end

  def install
    bin.install 'helloworld'
  end

  test do
    system "#{bin}/helloworld"
  end
end
